### ISSUE TITLE
3DMatch 

### ISSUE THREAD

**Issue by XuyangBai** [Yochengliu/awesome-point-cloud-analysis#6]
Thank you for your sharing. I think this paper [3DMatch: Learning Local Geometric Descriptors from RGB-D Reconstructions](https://arxiv.org/pdf/1603.08182.pdf) and the [dataset](http://3dmatch.cs.princeton.edu/) is also worth noticing.

**Comment by Yochengliu** [comment]
This is exactly an awesome work! Many thanks to your sharing :D
